[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
feekit = "9EMWVqoVNW9armPPwiY7DtW7kgQ14LTgk8F3mCkMZ11C"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/feekit"]

[scripts]
test = "cargo test --manifest-path programs/feekit/Cargo.toml -- --nocapture"
